# Project configuration
name: coffee_shop
version: '1.0.0'

# Profile to use
profile: 'coffee_shop_akwany'

# Paths for dbt to look for models and other resources
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configure models
models:
  coffee_shop_akwany:
    staging:
      +materialized: view  # Set default materialization for staging models
      github:
        +enabled: true      # Ensure GitHub staging models are recognized
        +materialized: view  # If needed, override for this subfolder
